apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
      version: canary
  template:
    metadata:
      labels:
        app: flaskapp
        version: canary
    spec:
      containers:
        - name: sampleapp
          image: docker.io/azimuth3d/flaskapp:canary:${TAG}
          imagePullPolicy: Always
